version: 1.2
service:
  subclass: DOCKER_COMPOSE
  name: DICOM viewer
  description: |
    DICOM Viewer
  files:
     - docker-compose.yml
     - localrun.yaml
     - README.md
     - config/nginx-with-proxy.conf
     - config/orthanc.json

  scripts:
    start: "docker-compose up -d"
    port: "echo 3000"
    stop: "docker-compose down"

  environment:
    DATA_DIR:
        description: Overrides the location of the data. Only used for running locally.
